version: '3.8'
services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    ports:
      - 8080:8080
    environment:
      - Node_ENV=production
    volumes:
      - /home/luna/dashy_docker/conf.yml:/app/user-data/conf.yml
      - /home/luna/dashy_docker/dashboard-icons/png:/app/public/item-icons/icons
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s